### ISSUE TITLE
not working with Python-Markdown 3.4.1

### ISSUE THREAD

**Issue by na-trium-144** [FND/markdown-checklist#18]
I found this extension not working with the latest Python-Markdown(3.4.1).
I have no problem since I switched it to 3.3.7, but it would be better if it works with the latest version. Thanks.

```
/ # python -m markdown -x markdown_checklist.extension
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/markdown/__main__.py", line 151, in <module>
    run()
  File "/usr/local/lib/python3.10/site-packages/markdown/__main__.py", line 145, in run
    markdown.markdownFromFile(**options)
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 404, in markdownFromFile
    md = Markdown(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 125, in registerExtensions
    ext.extendMarkdown(self)
TypeError: ChecklistExtension.extendMarkdown() missing 1 required positional argument: 'md_globals'
/ # python -m markdown --version
__main__.py 3.4.1
```

**Comment by FND** [comment]
This should be fixed with 44ec521ae29341906b1f2829a3a3ff2c6ed60584 - however, since I haven't touched this project in ages, I can't easily make a release. Could you check whether this change works for you?

**Comment by na-trium-144** [comment]
Thanks. I cloned the repository and installed with pip.
Unfortunately, I got another error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/markdown/__main__.py", line 151, in <module>
    run()
  File "/usr/local/lib/python3.10/site-packages/markdown/__main__.py", line 145, in run
    markdown.markdownFromFile(**options)
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 404, in markdownFromFile
    md = Markdown(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 125, in registerExtensions
    ext.extendMarkdown(self)
  File "/usr/local/lib/python3.10/site-packages/markdown_checklist/extension.py", line 29, in extendMarkdown
    md.postprocessors.add('checklist', postprocessor, '>raw_html')
AttributeError: 'Registry' object has no attribute 'add'
```
So I checked the Python-Markdown release notes and replaced `md.postprocessors.add` with `md.postprocessors.register` and this was fixed.

However, I got one more error when I tried to convert markdown.
Sorry for inconvenience but could you fix this too?
```
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 290, in convert
    for pp in self.postprocessors:
  File "/usr/local/lib/python3.10/site-packages/markdown/util.py", line 282, in __iter__
    self._sort()
  File "/usr/local/lib/python3.10/site-packages/markdown/util.py", line 357, in _sort
    self._priority.sort(key=lambda item: item.priority, reverse=True)
TypeError: '<' not supported between instances of 'int' and 'str'

```

**Comment by FND** [comment]
Thanks for looking into that. Seems like the API has changed so that additionally, we need to pass a priority now:

```diff
-        md.postprocessors.add('checklist', postprocessor, '>raw_html')
+        md.postprocessors.register(postprocessor, 'checklist', 50)
```

However, while that makes tests pass, I'm not sure whether we need a replacement for the `>raw_html` directive(?) there: The documentation doesn't make it obvious how this argument worked in the first place and I can't remember either...

**Comment by na-trium-144** [comment]
> Thanks for looking into that. Seems like the API has changed so that additionally, we need to pass a priority now:
> 
> ```diff
> -        md.postprocessors.add('checklist', postprocessor, '>raw_html')
> +        md.postprocessors.register(postprocessor, 'checklist', 50)
> ```

This worked fine. Thank you!

**Comment by FND** [comment]
Thanks for working with me there. 3cad617da8842e4aefc9bdd3265c18da65a28d05 is now [released](https://pypi.org/project/markdown-checklist/) as v0.4.4.
